#-------------------------------------------------------------------------
# TITLE:
#    pkgIndex.tcl
#
# PROJECT:
#    athena-mars
#
# DESCRIPTION:
#    app_cmtool(n) package index file
#
#    Generated by Kite.
#-------------------------------------------------------------------------

# -kite-ifneeded-start  DO NOT EDIT THIS BLOCK BY HAND
package ifneeded app_cmtool 3.0.16 [list source [file join $dir pkgModules.tcl]]
# -kite-ifneeded-end


