#-------------------------------------------------------------------------
# TITLE:
#    pkgIndex.tcl
#
# PROJECT:
#    athena-mars
#
# DESCRIPTION:
#    marsutil(n) package index file
#
#    Generated by Kite from pkgIndex.template.
#-------------------------------------------------------------------------

# -kite-start-ifneeded  DO NOT EDIT THIS BLOCK BY HAND
package ifneeded marsutil 3.0a1 [list source [file join $dir pkgModules.tcl]]
# -kite-end-ifneeded


