#-----------------------------------------------------------------------
# TITLE:
#    pkgModules.tcl
#
# PROJECT:
#    athena-mars
#
# DESCRIPTION:
#    marsutil(n) package modules file
#
#    Generated by Kite from pkgModules.template.
#-----------------------------------------------------------------------

#-----------------------------------------------------------------------
# Package Definition

# -kite-provide-start  DO NOT EDIT THIS BLOCK BY HAND
package provide marsutil 3.0a2
# -kite-provide-end

#-----------------------------------------------------------------------
# Required Packages

# -kite-require-start  REQUIRE EXTERNAL PACKAGES HERE
package require snit 2.3
package require textutil::expander 1.3.1
# -kite-require-end


#-----------------------------------------------------------------------
# Namespace definition

namespace eval ::marsutil:: {
    variable library [file dirname [info script]]
}

#-----------------------------------------------------------------------
# Modules

source [file join $::marsutil::library marsmisc.tcl   ]
source [file join $::marsutil::library tclchecker.tcl ]
source [file join $::marsutil::library smartinterp.tcl]
source [file join $::marsutil::library template.tcl   ]
source [file join $::marsutil::library ehtml.tcl      ]
source [file join $::marsutil::library manpage.tcl    ]
source [file join $::marsutil::library marsdoc.tcl    ]
