#-----------------------------------------------------------------------
# TITLE:
#    pkgModules.tcl
#
# PROJECT:
#    athena-mars
#
# DESCRIPTION:
#    marsutil(n) package modules file
#
#    Generated by Kite from pkgModules.template.
#-----------------------------------------------------------------------

#-----------------------------------------------------------------------
# Package Definition

# -kite-start-provide  DO NOT EDIT THIS BLOCK BY HAND
package provide marsutil 3.0a1
# -kite-end-provide

#-----------------------------------------------------------------------
# Required Packages

# -kite-start-require  DO NOT EDIT THIS BLOCK BY HAND
package require snit 2.3
package require textutil::expander 1.3.1
# -kite-end-require


#-----------------------------------------------------------------------
# Namespace definition

namespace eval ::marsutil:: {
    variable library [file dirname [info script]]
}

#-----------------------------------------------------------------------
# Modules

source [file join $::marsutil::library marsmisc.tcl   ]
source [file join $::marsutil::library tclchecker.tcl ]
source [file join $::marsutil::library smartinterp.tcl]
source [file join $::marsutil::library template.tcl   ]
source [file join $::marsutil::library ehtml.tcl      ]
