#!/bin/sh
# -*-tcl-*-
# The next line restarts using tclsh \
exec tclsh "$0" "$@"

set target [lindex $argv 0]
puts "Looking for $target"

proc findit {target args} {
    foreach pattern $args {
        set files [glob -nocomplain $pattern]
        if {[llength $files] == 0} {
            return
        }

        puts "*** [pwd]: $pattern"
        catch {puts [exec grep $target {*}$files]}   
    }
}

cd ~/mars/lib
findit $target */*.tcl */*.test */*.sql

cd ~/athena/lib
findit $target */*.tcl */*/*.tcl */*.sql */*/*.sql

cd ~/athena/test/app_sim
findit $target *.tcl *.test




