#-------------------------------------------------------------------------
# TITLE:
#    pkgIndex.tcl
#
# PROJECT:
#    athena-mars
#
# DESCRIPTION:
#    simlib(n) package index file
#
#    Generated by Kite.
#-------------------------------------------------------------------------

# -kite-ifneeded-start  DO NOT EDIT THIS BLOCK BY HAND
package ifneeded simlib 3.0.23 [list source [file join $dir pkgModules.tcl]]
# -kite-ifneeded-end





