#-------------------------------------------------------------------------
# TITLE:
#    pkgIndex.tcl
#
# PROJECT:
#    athena-mars - Mars Simulation Support Library
#
# DESCRIPTION:
#    kiteinfo(n) package index file
#
#    Generated by Kite.
#-------------------------------------------------------------------------

package ifneeded kiteinfo 1.0 [list source [file join $dir pkgModules.tcl]]
