#-----------------------------------------------------------------------
# TITLE:
#    marsicons.tcl
#
# AUTHOR:
#    Will Duquette
#
# DESCRIPTION:
#    marsgui(n) package: standard icons
#
#    This module defines a set of standard icons for use in buttons,
#    etc.  All icons are defined in the ::marsgui::icon namespace; none
#    are exported.
#
#-----------------------------------------------------------------------

#-----------------------------------------------------------------------
# Icon definitions

namespace eval ::marsgui::icon:: {
    namespace import ::marsgui::mkicon
    
    mkicon ::marsgui::icon::clear {
        ...XXXXX...
        ..XXXXXXX..
        .XX.XXX.XX.
        XX...X...XX
        XXX.....XXX
        XXXX...XXXX
        XXX.....XXX
        XX...X...XX
        .XX.XXX.XX.
        ..XXXXXXX..
        ...XXXXX...
        ...........
    } { . trans X black} d { X gray }
    
    mkicon ::marsgui::icon::clock {
        ....XXXXX....
        ..XX.....XX..
        .X....X....X.
        .X....X....X.
        X.....X.....X
        X.....X.....X
        X.....XXX...X
        X...........X
        X...........X
        .X.........X.
        .X.........X.
        ..XX.....XX..
        ..XXXXXXXXX..
        .XXXXXXXXXXX.
    } { . trans X black} d { X gray}
    
    mkicon ::marsgui::icon::filter {
        ........XXXXX...
        .......X.X.X.X..
        ......X.X.X.X.X.
        .....X.X.X.X.X.X
        .....XX.X.X.X.XX
        .....X.X.X.X.X.X
        .....XX.X.X.X.XX
        .....X.X.X.X.X.X
        ......X.X.X.X.X.
        .....XXX.X.X.X..
        ....XXX.XXXXX...
        ...XXX..........
        ..XXX....XXXXXXX
        .XXX......XXXXX.
        XXX........XXX..
        XX..........X...
    } {
        . trans
        X black
    }

    mkicon ::marsgui::icon::search {
        ........XXXXX...
        .......X.....X..
        ......X..XXX..X.
        .....X..X...X..X
        .....X.........X
        .....X.........X
        .....X.........X
        .....X.........X
        ......X.......X.
        .....XXX.....X..
        ....XXX.XXXXX...
        ...XXX..........
        ..XXX....XXXXXXX
        .XXX......XXXXX.
        XXX........XXX..
        XX..........X...
    } {
        . trans
        X black
    }
    
    mkicon ::marsgui::icon::autoscroll_on {
        ..XXXXXXXXXX..
        ..X........X..
        ..X.XX.XXX.X..
        ..X........X..
        ..X.XX.XXX.X..
        ..X........X..
        ..X.XX.XXX.X..
        ..X........X..
        XXXXXXXXXXXXXX
        X.X........X.X
        X.X.XX.XXX.X.X
        X.XXXXXXXXXX.X
        X............X
        XXXXXXXXXXXXXX
    } { . trans X black } d { X gray }

    mkicon ::marsgui::icon::autoscroll_off {
        ..XXXXXXXXXX..
        ..X........X..
        XXXXXXXXXXXXXX
        X.X........X.X
        X.X.XX.XXX.X.X
        X.X........X.X
        X.X.XX.XXX.X.X
        XXXXXXXXXXXXXX
        ..X........X..
        ..X.XX.XXX.X..
        ..X........X..
        ..XXXXXXXXXX..
        ..............
        ..............
    } { . trans X black } d { X gray }
    
    mkicon ::marsgui::icon::locked {
        ..............
        ...XXXXXXXX...
        ..XXXXXXXXXX..
        ..XX......XX..
        ..XX......XX..
        ..XX......XX..
        ..XX......XX..
        XXXXXXXXXXXXXX
        X............X
        X.XXXXXXXXXX.X
        X............X
        X.XXXXXXXXXX.X
        X............X
        X.XXXXXXXXXX.X
        X............X
        XXXXXXXXXXXXXX
    } { . trans X black } d { X gray }

    mkicon ::marsgui::icon::unlocked {
        ...XXXXXXXX...
        ..XXXXXXXXXX..
        ..XX......XX..
        ..XX......XX..
        ..XX..........
        ..XX..........
        ..XX..........
        XXXXXXXXXXXXXX
        X............X
        X.XXXXXXXXXX.X
        X............X
        X.XXXXXXXXXX.X
        X............X
        X.XXXXXXXXXX.X
        X............X
        XXXXXXXXXXXXXX
    } { . trans X black } d { X gray }

    mkicon ::marsgui::icon::tridown {
        ................
        ................
        ................
        .XXXXXXXXXXXXXX.
        ..XXXXXXXXXXXX..
        ...XXXXXXXXXX...
        ....XXXXXXXX....
        .....XXXXXX.....
        ......XXXX......
        .......XX.......
        ................
        ................
        ................
        ................
        ................
        ................
    } {
        . trans
        X black
    }

    mkicon ::marsgui::icon::onoff {
        .......................
        .......................
        ..........XXX..........
        .......X..XXX..X.......
        .....XXX..XXX..XXX.....
        ....XXX...XXX...XXX....
        ....XX....XXX....XX....
        ...XX.....XXX.....XX...
        ...XX.....XXX.....XX...
        ..XX......XXX......XX..
        ..XX...............XX..
        ..XX...............XX..
        ..XX...............XX..
        ..XX...............XX..
        ...XX.............XX...
        ...XX.............XX...
        ....XX...........XXX...
        ....XXX.........XXX....
        .....XXXX.....XXXX.....
        .......XXXXXXXXX.......
        .........XXXXX.........
        .......................
    } { . trans  X black } d { X gray }

    mkicon ::marsgui::icon::pencil22 {
        ......................
        ......................
        ...............XXX....
        ..............XeeeX...
        .............XeeeeeX..
        ............X,XeeeeX..
        ...........X,,,XeeeX..
        ..........X,,,X,XeX...
        .........X,,,X,,,X....
        ........X,,,X,,,X.....
        .......X,,,X,,,X......
        ......X,,,X,,,X.......
        .....X,,,X,,,X........
        ....XwX,X,,,X.........
        ....XwwX,,,X..........
        ...XwwwwX,X...........
        ...XwwwwwX............
        ...XXwwXX.............
        ..XXXXX...............
        ..XX..................
        ......................
        ......................
    } {
        .  trans
        X  #000000
        e  #E77F7F
        ,  #EFB311
        w  #BDA565
    } d { X gray  e gray  w gray82  , gray82 }

    mkicon ::marsgui::icon::pencil022 {
        ......................
        ......................
        ...............XXX....
        ..............XeeeX...
        .............XeeeeeX..
        ............X,XeeeeX..
        ...........X,,,XeeeX..
        ..........X,,,X,XeX...
        .........X,,,X,,,X....
        ........X,,,X,,,X.....
        .......X,,,X,,,X......
        ......X,,,X,,,X.......
        .....X,,,X,,,X........
        ....XwX,X,,,X..XXXX...
        ....XwwX,,,X..X....X..
        ...XwwwwX,X...X...XX..
        ...XwwwwwX....X..X.X..
        ...XXwwXX.....X.X..X..
        ..XXXXX.......XX...X..
        ..XX...........XXXX...
        ......................
        ......................
    } {
        .  trans
        X  #000000
        e  #E77F7F
        ,  #EFB311
        w  #BDA565
    } d { X gray  e gray  w gray82  , gray82 }

    mkicon ::marsgui::icon::pencila22 {
        ......................
        ......................
        ...............XXX....
        ..............XeeeX...
        .............XeeeeeX..
        ............X,XeeeeX..
        ...........X,,,XeeeX..
        ..........X,,,X,XeX...
        .........X,,,X,,,X....
        ........X,,,X,,,X.....
        .......X,,,X,,,X......
        ......X,,,X,,,X.......
        .....X,,,X,,,X........
        ....XwX,X,,,X..XXXX...
        ....XwwX,,,X..X....X..
        ...XwwwwX,X...X....X..
        ...XwwwwwX....XXXXXX..
        ...XXwwXX.....X....X..
        ..XXXXX.......X....X..
        ..XX..........X....X..
        ......................
        ......................
    } {
        .  trans
        X  #000000
        e  #E77F7F
        ,  #EFB311
        w  #BDA565
    } d { X gray  e gray  w gray82  , gray82 }

    mkicon ::marsgui::icon::pencilb22 {
        ......................
        ......................
        ...............XXX....
        ..............XeeeX...
        .............XeeeeeX..
        ............X,XeeeeX..
        ...........X,,,XeeeX..
        ..........X,,,X,XeX...
        .........X,,,X,,,X....
        ........X,,,X,,,X.....
        .......X,,,X,,,X......
        ......X,,,X,,,X.......
        .....X,,,X,,,X........
        ....XwX,X,,,X.XXXXX...
        ....XwwX,,,X..X....X..
        ...XwwwwX,X...X....X..
        ...XwwwwwX....XXXXX...
        ...XXwwXX.....X....X..
        ..XXXXX.......X....X..
        ..XX..........XXXXX...
        ......................
        ......................
    } {
        .  trans
        X  #000000
        e  #E77F7F
        ,  #EFB311
        w  #BDA565
    } d { X gray  e gray  w gray82  , gray82 }

    mkicon ::marsgui::icon::pencili22 {
        ......................
        ......................
        ...............XXX....
        ..............XeeeX...
        .............XeeeeeX..
        ............X,XeeeeX..
        ...........X,,,XeeeX..
        ..........X,,,X,XeX...
        .........X,,,X,,,X....
        ........X,,,X,,,X.....
        .......X,,,X,,,X......
        ......X,,,X,,,X.......
        .....X,,,X,,,X........
        ....XwX,X,,,X..XXXXX..
        ....XwwX,,,X.....X....
        ...XwwwwX,X......X....
        ...XwwwwwX.......X....
        ...XXwwXX........X....
        ..XXXXX..........X....
        ..XX...........XXXXX..
        ......................
        ......................
    } {
        .  trans
        X  #000000
        e  #E77F7F
        ,  #EFB311
        w  #BDA565
    } d { X gray  e gray  w gray82  , gray82 }

    mkicon ::marsgui::icon::pencilm22 {
        ......................
        ......................
        ...............XXX....
        ..............XeeeX...
        .............XeeeeeX..
        ............X,XeeeeX..
        ...........X,,,XeeeX..
        ..........X,,,X,XeX...
        .........X,,,X,,,X....
        ........X,,,X,,,X.....
        .......X,,,X,,,X......
        ......X,,,X,,,X.......
        .....X,,,X,,,X........
        ....XwX,X,,,X.........
        ....XwwX,,,X..X....X..
        ...XwwwwX,X...XX..XX..
        ...XwwwwwX....X.XX.X..
        ...XXwwXX.....X....X..
        ..XXXXX.......X....X..
        ..XX..........X....X..
        ..............X....X..
        ......................
    } {
        .  trans
        X  #000000
        e  #E77F7F
        ,  #EFB311
        w  #BDA565
    } d { X gray  e gray  w gray82  , gray82 }

    mkicon ::marsgui::icon::pencils22 {
        ......................
        ......................
        ...............XXX....
        ..............XeeeX...
        .............XeeeeeX..
        ............X,XeeeeX..
        ...........X,,,XeeeX..
        ..........X,,,X,XeX...
        .........X,,,X,,,X....
        ........X,,,X,,,X.....
        .......X,,,X,,,X......
        ......X,,,X,,,X.......
        .....X,,,X,,,X........
        ....XwX,X,,,X..XXXX...
        ....XwwX,,,X..X....X..
        ...XwwwwX,X...X.......
        ...XwwwwwX.....XXXX...
        ...XXwwXX..........X..
        ..XXXXX.......X....X..
        ..XX...........XXXX...
        ......................
        ......................
    } {
        .  trans
        X  #000000
        e  #E77F7F
        ,  #EFB311
        w  #BDA565
    } d { X gray  e gray  w gray82  , gray82 }

    mkicon ::marsgui::icon::pencilt22 {
        ......................
        ......................
        ...............XXX....
        ..............XeeeX...
        .............XeeeeeX..
        ............X,XeeeeX..
        ...........X,,,XeeeX..
        ..........X,,,X,XeX...
        .........X,,,X,,,X....
        ........X,,,X,,,X.....
        .......X,,,X,,,X......
        ......X,,,X,,,X.......
        .....X,,,X,,,X........
        ....XwX,X,,,X..XXXXX..
        ....XwwX,,,X.....X....
        ...XwwwwX,X......X....
        ...XwwwwwX.......X....
        ...XXwwXX........X....
        ..XXXXX..........X....
        ..XX.............X....
        ......................
        ......................
    } {
        .  trans
        X  #000000
        e  #E77F7F
        ,  #EFB311
        w  #BDA565
    } d { X gray  e gray  w gray82  , gray82 }



    mkicon ::marsgui::icon::pencil12 {
        ............
        .......XX...
        ......X,,X..
        .....X,,,X..
        ....X,,,X...
        ...X,,,X....
        ..X,,,X.....
        .XwX,X......
        .XwwX.......
        .XXX........
        XX..........
        X...........
    } { . trans 
        X black 
        ,  #EFB311
        w  #BDA565
    } d {X gray w gray82 , gray82}
    
    mkicon ::marsgui::icon::plus22 {
        ......................
        ......................
        ......................
        .........XXXX.........
        .........XXXX.........
        .........XXXX.........
        .........XXXX.........
        .........XXXX.........
        .........XXXX.........
        ...XXXXXXXXXXXXXXXX...
        ...XXXXXXXXXXXXXXXX...
        ...XXXXXXXXXXXXXXXX...
        ...XXXXXXXXXXXXXXXX...
        .........XXXX.........
        .........XXXX.........
        .........XXXX.........
        .........XXXX.........
        .........XXXX.........
        .........XXXX.........
        ......................
        ......................
        ......................
    } { . trans  X black } d { X gray }


    mkicon ::marsgui::icon::plusa22 {
        ......................
        ......................
        ......................
        .........XXXX.........
        .........XXXX.........
        .........XXXX.........
        .........XXXX.........
        .........XXXX.........
        .........XXXX.........
        ...XXXXXXXXXXXXXXXX...
        ...XXXXXXXXXXXXXXXX...
        ...XXXXXXXXXXXXXXXX...
        ...XXXXXXXXXXXXXXXX...
        .........XXXX.........
        .........XXXX...XXXX..
        .........XXXX..X....X.
        .........XXXX..X....X.
        .........XXXX..XXXXXX.
        .........XXXX..X....X.
        ...............X....X.
        ...............X....X.
        ......................
    } { . trans  X black } d { X gray }


    mkicon ::marsgui::icon::plusc22 {
        ......................
        ......................
        ......................
        .........XXXX.........
        .........XXXX.........
        .........XXXX.........
        .........XXXX.........
        .........XXXX.........
        .........XXXX.........
        ...XXXXXXXXXXXXXXXX...
        ...XXXXXXXXXXXXXXXX...
        ...XXXXXXXXXXXXXXXX...
        ...XXXXXXXXXXXXXXXX...
        .........XXXX.........
        .........XXXX...XXXX..
        .........XXXX..X......
        .........XXXX..X......
        .........XXXX..X......
        .........XXXX...XXXX..
        ......................
        ......................
        ......................
    } { . trans  X black } d { X gray }

    mkicon ::marsgui::icon::plusg22 {
        ......................
        ......................
        ......................
        .........XXXX.........
        .........XXXX.........
        .........XXXX.........
        .........XXXX.........
        .........XXXX.........
        .........XXXX.........
        ...XXXXXXXXXXXXXXXX...
        ...XXXXXXXXXXXXXXXX...
        ...XXXXXXXXXXXXXXXX...
        ...XXXXXXXXXXXXXXXX...
        .........XXXX.........
        .........XXXX...XXXX..
        .........XXXX..X......
        .........XXXX..X..XX..
        .........XXXX..X...X..
        .........XXXX...XXXX..
        ......................
        ......................
        ......................
    } { . trans  X black } d { X gray }

    mkicon ::marsgui::icon::plush22 {
        ......................
        ......................
        ......................
        .........XXXX.........
        .........XXXX.........
        .........XXXX.........
        .........XXXX.........
        .........XXXX.........
        .........XXXX.........
        ...XXXXXXXXXXXXXXXX...
        ...XXXXXXXXXXXXXXXX...
        ...XXXXXXXXXXXXXXXX...
        ...XXXXXXXXXXXXXXXX...
        .........XXXX.........
        .........XXXX..X...X..
        .........XXXX..X...X..
        .........XXXX..XXXXX..
        .........XXXX..X...X..
        .........XXXX..X...X..
        ......................
        ......................
        ......................
    } { . trans  X black } d { X gray }

    mkicon ::marsgui::icon::plusi22 {
        ......................
        ......................
        ......................
        .........XXXX.........
        .........XXXX.........
        .........XXXX.........
        .........XXXX.........
        .........XXXX.........
        .........XXXX.........
        ...XXXXXXXXXXXXXXXX...
        ...XXXXXXXXXXXXXXXX...
        ...XXXXXXXXXXXXXXXX...
        ...XXXXXXXXXXXXXXXX...
        .........XXXX.........
        .........XXXX..XXXXX..
        .........XXXX....X....
        .........XXXX....X....
        .........XXXX....X....
        .........XXXX..XXXXX..
        ......................
        ......................
        ......................
    } { . trans  X black } d { X gray }

    mkicon ::marsgui::icon::plusp22 {
        ......................
        ......................
        ......................
        .........XXXX.........
        .........XXXX.........
        .........XXXX.........
        .........XXXX.........
        .........XXXX.........
        .........XXXX.........
        ...XXXXXXXXXXXXXXXX...
        ...XXXXXXXXXXXXXXXX...
        ...XXXXXXXXXXXXXXXX...
        ...XXXXXXXXXXXXXXXX...
        .........XXXX.........
        .........XXXX..XXXXX..
        .........XXXX..X...X..
        .........XXXX..XXXXX..
        .........XXXX..X......
        .........XXXX..X......
        ......................
        ......................
        ......................
    } { . trans  X black } d { X gray }

    mkicon ::marsgui::icon::pluss22 {
        ......................
        ......................
        ......................
        .........XXXX.........
        .........XXXX.........
        .........XXXX.........
        .........XXXX.........
        .........XXXX.........
        .........XXXX.........
        ...XXXXXXXXXXXXXXXX...
        ...XXXXXXXXXXXXXXXX...
        ...XXXXXXXXXXXXXXXX...
        ...XXXXXXXXXXXXXXXX...
        .........XXXX.........
        .........XXXX...XXXX..
        .........XXXX..X....X.
        .........XXXX..X......
        .........XXXX...XXXX..
        .........XXXX.......X.
        ...............X....X.
        ................XXXX..
        ......................
    } { . trans  X black } d { X gray }


    mkicon ::marsgui::icon::plust22 {
        ......................
        ......................
        ......................
        .........XXXX.........
        .........XXXX.........
        .........XXXX.........
        .........XXXX.........
        .........XXXX.........
        .........XXXX.........
        ...XXXXXXXXXXXXXXXX...
        ...XXXXXXXXXXXXXXXX...
        ...XXXXXXXXXXXXXXXX...
        ...XXXXXXXXXXXXXXXX...
        .........XXXX.........
        .........XXXX..XXXXX..
        .........XXXX....X....
        .........XXXX....X....
        .........XXXX....X....
        .........XXXX....X....
        ......................
        ......................
        ......................
    } { . trans  X black } d { X gray }

    mkicon ::marsgui::icon::trash22 {
        ....................
        ....................
        .......XXXX........
        ......X....X.......
        ..XXXXXXXXXXXXXX..
        .XeeeeeeeeeeeeeeX.
        .XXXXXXXXXXXXXXXX.
        ..XeXeeXeeXeeXeX..
        ..XeXeeXeeXeeXeX..
        ..XeXeeXeeXeeXeX..
        ..XeXeeXeeXeeXeX..
        ..XeXeeXeeXeeXeX..
        ..XeXeeXeeXeeXeX..
        ..XeXeeXeeXeeXeX..
        ..XeXeeXeeXeeXeX..
        ..XeXeeXeeXeeXeX..
        ..XeXeeXeeXeeXeX..
        ..XeXeeXeeXeeXeX..
        ..XeXeeXeeXeeXeX..
        ..XeXeeXeeXeeXeX..
        ..XXXXXXXXXXXXXX..
        ....................
    } {
        .  trans
        X  black
        e  gray
    } d { X gray }

    mkicon ::marsgui::icon::question22 {
        ......................
        ......................
        ........XXXXXX........
        ......XXXXXXXXXX......
        .....XXXXXXXXXXXX.....
        ....XXXXX....XXXXX....
        ....XXXX......XXXX....
        .....XX.......XXXX....
        .............XXXX.....
        ............XXXX......
        ...........XXXX.......
        ..........XXXX........
        .........XXXX.........
        .........XXXX.........
        ..........XX..........
        ......................
        ..........XX..........
        .........XXXX.........
        .........XXXX.........
        ..........XX..........
        ......................
        ......................
    } {
        .  trans
        X  #000000
    }

    mkicon ::marsgui::icon::exclaim22 {
        ......................
        ......................
        .........XXXX.........
        ........XXXXXX........
        .......XXXXXXXX.......
        .......XXXXXXXX.......
        .......XXXXXXXX.......
        ........XXXXXX........
        ........XXXXXX........
        .........XXXX.........
        .........XXXX.........
        .........XXXX.........
        ..........XX..........
        ..........XX..........
        ..........XX..........
        ......................
        ..........XX..........
        .........XXXX.........
        .........XXXX.........
        ..........XX..........
        ......................
        ......................
    } {
        .  trans
        X  #000000
    }

    mkicon ::marsgui::icon::a22 {
        ......................
        ......................
        ......................
        .........XXXX.........
        .........XXXX.........
        ........XXXXXX........
        ........XXXXXX........
        .......XXX..XXX.......
        .......XXX..XXX.......
        ......XXX....XXX......
        ......XXX....XXX......
        .....XXX......XXX.....
        .....XXX......XXX.....
        ....XXXXXXXXXXXXXX....
        ....XXXXXXXXXXXXXX....
        ...XXX..........XXX...
        ...XXX..........XXX...
        ..XXX............XXX..
        ..XXX............XXX..
        ......................
        ......................
        ......................
    } { . trans  X black } d { X gray }


    mkicon ::marsgui::icon::x22 {
        ......................
        ......................
        ......................
        ...XXX..........XXX...
        ...XXXX........XXXX...
        ...XXXXX......XXXXX...
        ....XXXXX....XXXXX....
        .....XXXXX..XXXXX.....
        ......XXXXXXXXXX......
        .......XXXXXXXX.......
        ........XXXXXX........
        ........XXXXXX........
        .......XXXXXXXX.......
        ......XXXXXXXXXX......
        .....XXXXX..XXXXX.....
        ....XXXXX....XXXXX....
        ...XXXXX......XXXXX...
        ...XXXX........XXXX...
        ...XXX..........XXX...
        ......................
        ......................
        ......................
    } { . trans  X  "#FF0000" } d { X gray }

    mkicon ::marsgui::icon::check22 {
        ......................
        ......................
        ......................
        ......................
        .................XX...
        ...X...........XXX....
        ...XX........XXXX.....
        ....XX.....XXXXX......
        ....XXX..XXXXXX.......
        ....XXXXXXXXXX........
        ....XXXXXXXXX.........
        .....XXXXXXX..........
        .....XXXXXX...........
        .....XXXXX............
        .....XXXX.............
        ......XX..............
        ......X...............
        ......................
        ......................
        ......................
        ......................
        ......................
    } { . trans  X "#009900" } d { X gray }

    mkicon ::marsgui::icon::play22 {
        ......................
        ......................
        ......................
        ....XX................
        ....XXXX..............
        ....XXXXXX............
        ....XXXXXXXX..........
        ....XXXXXXXXXX........
        ....XXXXXXXXXXXX......
        ....XXXXXXXXXXXXXX....
        ....XXXXXXXXXXXX......
        ....XXXXXXXXXX........
        ....XXXXXXXX..........
        ....XXXXXX............
        ....XXXX..............
        ....XX................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
    } { . trans  X black } d { X gray }

    mkicon ::marsgui::icon::pause22 {
        ......................
        ......................
        ......................
        .....XXXX....XXXX.....
        .....XXXX....XXXX.....
        .....XXXX....XXXX.....
        .....XXXX....XXXX.....
        .....XXXX....XXXX.....
        .....XXXX....XXXX.....
        .....XXXX....XXXX.....
        .....XXXX....XXXX.....
        .....XXXX....XXXX.....
        .....XXXX....XXXX.....
        .....XXXX....XXXX.....
        .....XXXX....XXXX.....
        .....XXXX....XXXX.....
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
    } { . trans  X black } d { X gray }

    mkicon ::marsgui::icon::rewind22 {
        ......................
        ......................
        ......................
        ...X............XX....
        ...X..........XXXX....
        ...X........XXXXXX....
        ...X......XXXXXXXX....
        ...X....XXXXXXXXXX....
        ...X..XXXXXXXXXXXX....
        ...XXXXXXXXXXXXXXX....
        ...X..XXXXXXXXXXXX....
        ...X....XXXXXXXXXX....
        ...X......XXXXXXXX....
        ...X........XXXXXX....
        ...X..........XXXX....
        ...X............XX....
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
    } { . trans  X black } d { X gray }


    mkicon ::marsgui::icon::first16 {
        ................
        .X.....X.....X..
        .X....XX....XX..
        .X...XXX...XXX..
        .X..XXXX..XXXX..
        .X.XXXXX.XXXXX..
        .XXXXXXXXXXXXX..
        .X.XXXXX.XXXXX..
        .X..XXXX..XXXX..
        .X...XXX...XXX..
        .X....XX....XX..
        .X.....X.....X..
        ................
        ................
        ................
        ................
    } { .  trans  X black } d { X gray }


    mkicon ::marsgui::icon::prev16 {
        ................
        .......X.....X..
        ......XX....XX..
        .....XXX...XXX..
        ....XXXX..XXXX..
        ...XXXXX.XXXXX..
        ..XXXXXXXXXXXX..
        ...XXXXX.XXXXX..
        ....XXXX..XXXX..
        .....XXX...XXX..
        ......XX....XX..
        .......X.....X..
        ................
        ................
        ................
        ................
    } { .  trans  X black } d { X gray }


    mkicon ::marsgui::icon::next16 {
        ................
        .X.....X........
        .XX....XX.......
        .XXX...XXX......
        .XXXX..XXXX.....
        .XXXXX.XXXXX....
        .XXXXXXXXXXXX...
        .XXXXX.XXXXX....
        .XXXX..XXXX.....
        .XXX...XXX......
        .XX....XX.......
        .X.....X........
        ................
        ................
        ................
        ................
    } { .  trans  X black } d { X gray }


    mkicon ::marsgui::icon::last16 {
        ................
        .X.....X.....X..
        .XX....XX....X..
        .XXX...XXX...X..
        .XXXX..XXXX..X..
        .XXXXX.XXXXX.X..
        .XXXXXXXXXXXXX..
        .XXXXX.XXXXX.X..
        .XXXX..XXXX..X..
        .XXX...XXX...X..
        .XX....XX....X..
        .X.....X.....X..
        ................
        ................
        ................
        ................
    } { .  trans  X black } d { X gray }

    mkicon ::marsgui::icon::gear {
        ........xXXx........
        ........XXXX........
        ...XXx.xXXXXx.xXX...
        ..XXXXXXXXXXXXXXXX..
        ..XXXXXXXXXXXXXXXX..
        ..xXXXXXXXXXXXXXXx..
        ...XXXXXx..xXXXXX...
        ..XXXXX......XXXXX..
        xXXXXXx......xXXXXXx
        XXXXXX........XXXXXX
        XXXXXX........XXXXXX
        xXXXXXx......xXXXXXx
        ..XXXXX......XXXXX..
        ...XXXXXx..xXXXXX...
        ..xXXXXXXXXXXXXXXx..
        ..XXXXXXXXXXXXXXXX..
        ..XXXXXXXXXXXXXXXX..
        ...XXx.xXXXXx.xXX...
        ........XXXX........
        ........xXXx........
    } { . trans  X black x gray} d { X gray x trans }

    mkicon ::marsgui::icon::totop {
        ......................
        ......................
        ...XXXXXXXXXXXXXXXX...
        ...XXXXXXXXXXXXXXXX...
        ..........XX..........
        .........XXXX.........
        ........XXXXXX........
        .......XX.XX.XX.......
        ......XX..XX..XX......
        .....XX...XX...XX.....
        ....XX....XX....XX....
        ..........XX..........
        ..........XX..........
        ..........XX..........
        ..........XX..........
        ..........XX..........
        ..........XX..........
        ..........XX..........
        ......................
        ......................
        ......................
        ......................
    } { . trans  X black } d { X gray }


    mkicon ::marsgui::icon::raise {
        ......................
        ......................
        ......................
        ......................
        ..........XX..........
        .........XXXX.........
        ........XXXXXX........
        .......XX.XX.XX.......
        ......XX..XX..XX......
        .....XX...XX...XX.....
        ....XX....XX....XX....
        ..........XX..........
        ..........XX..........
        ..........XX..........
        ..........XX..........
        ..........XX..........
        ..........XX..........
        ..........XX..........
        ......................
        ......................
        ......................
        ......................
    } { . trans  X black } d { X gray }


    mkicon ::marsgui::icon::lower {
        ......................
        ......................
        ......................
        ......................
        ..........XX..........
        ..........XX..........
        ..........XX..........
        ..........XX..........
        ..........XX..........
        ..........XX..........
        ..........XX..........
        ....XX....XX....XX....
        .....XX...XX...XX.....
        ......XX..XX..XX......
        .......XX.XX.XX.......
        ........XXXXXX........
        .........XXXX.........
        ..........XX..........
        ......................
        ......................
        ......................
        ......................
    } { . trans  X black } d { X gray }


    mkicon ::marsgui::icon::tobottom {
        ......................
        ......................
        ......................
        ......................
        ..........XX..........
        ..........XX..........
        ..........XX..........
        ..........XX..........
        ..........XX..........
        ..........XX..........
        ..........XX..........
        ....XX....XX....XX....
        .....XX...XX...XX.....
        ......XX..XX..XX......
        .......XX.XX.XX.......
        ........XXXXXX........
        .........XXXX.........
        ..........XX..........
        ...XXXXXXXXXXXXXXXX...
        ...XXXXXXXXXXXXXXXX...
        ......................
        ......................
    } { . trans  X black } d { X gray }


    mkicon ::marsgui::icon::left {
        ......................
        ......................
        ......................
        ......................
        ..........X...........
        .........XX...........
        ........XX............
        .......XX.............
        ......XX..............
        .....XX...............
        ....XXXXXXXXXXXXXX....
        ....XXXXXXXXXXXXXX....
        .....XX...............
        ......XX..............
        .......XX.............
        ........XX............
        .........XX...........
        ..........X...........
        ......................
        ......................
        ......................
        ......................
    } { . trans  X black } d { X gray }


    mkicon ::marsgui::icon::right {
        ......................
        ......................
        ......................
        ......................
        ...........X..........
        ...........XX.........
        ............XX........
        .............XX.......
        ..............XX......
        ...............XX.....
        ....XXXXXXXXXXXXXX....
        ....XXXXXXXXXXXXXX....
        ...............XX.....
        ..............XX......
        .............XX.......
        ............XX........
        ...........XX.........
        ...........X..........
        ......................
        ......................
        ......................
        ......................
    } { . trans  X black } d { X gray }


    mkicon ::marsgui::icon::thumbdown {
        .....................
        ........XXXXXXX......
        .......XXXXXXXXX.....
        ..XXXXXXXXXXXXXXX....
        ..XXXXXXXXXXXXXXXX...
        ..XXXXXXXXXXXXXXXXX..
        ..XXXXXXXXXXXXXXXXX..
        ..XXXXXXXXXXXXXXXXX..
        ..XXXXXXXXXXXXXXXXX..
        ..XXXXXXXXXXXXXXXXX..
        ......XXXXXXXXXXXXX..
        .......XXXXXXXXXXX...
        ........XXXXXXXXX....
        .........XXXXX.......
        .........XXXXX.......
        ..........XXXX.......
        ..........XXXX.......
        ...........XXXX......
        ...........XXXX......
        ............XXX......
        ............XXX......
        ............XXX......
        ............XX.......
        .....................
    } { . trans  X black } d { X gray }

    mkicon ::marsgui::icon::thumbdownred {
        .....................
        ........XXXXXXX......
        .......XXXXXXXXX.....
        ..XXXXXXXXXXXXXXX....
        ..XXXXXXXXXXXXXXXX...
        ..XXXXXXXXXXXXXXXXX..
        ..XXXXXXXXXXXXXXXXX..
        ..XXXXXXXXXXXXXXXXX..
        ..XXXXXXXXXXXXXXXXX..
        ..XXXXXXXXXXXXXXXXX..
        ......XXXXXXXXXXXXX..
        .......XXXXXXXXXXX...
        ........XXXXXXXXX....
        .........XXXXX.......
        .........XXXXX.......
        ..........XXXX.......
        ..........XXXX.......
        ...........XXXX......
        ...........XXXX......
        ............XXX......
        ............XXX......
        ............XXX......
        ............XX.......
        .....................
    } { . trans  X "#FF0000" } d { X gray }

    mkicon ::marsgui::icon::thumbup {
        .....................
        ............XX.......
        ............XXX......
        ............XXX......
        ............XXX......
        ...........XXXX......
        ...........XXXX......
        ..........XXXX.......
        ..........XXXX.......
        .........XXXXX.......
        .........XXXXX.......
        ........XXXXXXXXX....
        .......XXXXXXXXXXX...
        ......XXXXXXXXXXXXX..
        ..XXXXXXXXXXXXXXXXX..
        ..XXXXXXXXXXXXXXXXX..
        ..XXXXXXXXXXXXXXXXX..
        ..XXXXXXXXXXXXXXXXX..
        ..XXXXXXXXXXXXXXXXX..
        ..XXXXXXXXXXXXXXXX...
        ..XXXXXXXXXXXXXXX....
        .......XXXXXXXXX.....
        ........XXXXXXX......
        .....................
    } { . trans  X black } d { X gray }

    mkicon ::marsgui::icon::thumbupgreen {
        .....................
        ............XX.......
        ............XXX......
        ............XXX......
        ............XXX......
        ...........XXXX......
        ...........XXXX......
        ..........XXXX.......
        ..........XXXX.......
        .........XXXXX.......
        .........XXXXX.......
        ........XXXXXXXXX....
        .......XXXXXXXXXXX...
        ......XXXXXXXXXXXXX..
        ..XXXXXXXXXXXXXXXXX..
        ..XXXXXXXXXXXXXXXXX..
        ..XXXXXXXXXXXXXXXXX..
        ..XXXXXXXXXXXXXXXXX..
        ..XXXXXXXXXXXXXXXXX..
        ..XXXXXXXXXXXXXXXX...
        ..XXXXXXXXXXXXXXX....
        .......XXXXXXXXX.....
        ........XXXXXXX......
        .....................
    } { . trans  X "#009900" } d { X gray }

    mkicon ::marsgui::icon::smthumbupgreen {
        .....................
        ............XX.......
        ............XXX......
        ............XXX......
        ...........XXXX......
        ...........XXXX......
        ..........XXXX.......
        ..........XXXX.......
        .........XXXXX.......
        ........XXXXXXXX.....
        .......XXXXXXXXXX....
        ......XXXXXXXXXXXX...
        ..XXXXXXXXXXXXXXXX...
        ..XXXXXXXXXXXXXXXX...
        ..XXXXXXXXXXXXXXXX...
        ..XXXXXXXXXXXXXXXX...
        ..XXXXXXXXXXXXXXX....
        ..XXXXXXXXXXXXXX.....
        .......XXXXXXXX......
        .....................
    } { . trans  X "#009900" } d { X gray }

    mkicon ::marsgui::icon::smthumbdownred {
        .....................
        .......XXXXXXXX......
        ..XXXXXXXXXXXXXX.....
        ..XXXXXXXXXXXXXXX....
        ..XXXXXXXXXXXXXXXX...
        ..XXXXXXXXXXXXXXXX...
        ..XXXXXXXXXXXXXXXX...
        ..XXXXXXXXXXXXXXXX...
        ......XXXXXXXXXXXX...
        .......XXXXXXXXXX....
        ........XXXXXXXX.....
        .........XXXXX.......
        ..........XXXX.......
        ..........XXXX.......
        ...........XXXX......
        ...........XXXX......
        ............XXX......
        ............XXX......
        ............XX.......
        .....................
    } { . trans  X "#FF0000" } d { X gray }

    mkicon ::marsgui::icon::step {
        ......................
        ..........XX..........
        .........XXXX.........
        .........XXXX.........
        ..........XX..........
        ........XXX...........
        ......XXXXXX..........
        .....XXXXXXXX.........
        .....XX.XXXXX.........
        .....X..XXX.XX........
        .....X..XXX..XXXX.....
        .....X..XXX...........
        ........XXX...........
        ........XXXX..........
        ........X..XX.........
        .......XX...XX........
        ......XX.....XX.......
        .....XX.......XX......
        .....X.........X......
        ......................
        ......................
        ......................
    } { .  trans X  black } d { X gray }

    mkicon ::marsgui::icon::home22 {
        ......................
        ......................
        ......................
        ..........XX...XX.....
        .........XXXX..XX.....
        ........XXXXXX.XX.....
        .......XXXXXXXXXX.....
        ......XXXXXXXXXXX.....
        .....XXXXXXXXXXXX.....
        ....XXXXXXXXXXXXXX....
        ...XXXXXXXXXXXXXXXX...
        ..XXXXXXXXXXXXXXXXXX..
        .XXXXXXXXXXXXXXXXXXXX.
        ....XXXXXXXXXXXXXX....
        ....XXXXXXXXXXXXXX....
        ....XXXXXXXXXXXXXX....
        ....XXXXXXXXXXXXXX....
        ....XXXXXX..XXXXXX....
        ....XXXXXX..XXXXXX....
        ....XXXXXX..XXXXXX....
        ....XXXXXX..XXXXXX....
        ......................
    } {
        .  trans
        X  #000000
    } d { X gray }

    mkicon ::marsgui::icon::back {
        ......................
        ......................
        ..........X...........
        .........XX...........
        ........XXX...........
        .......XXXX...........
        ......XXXXXXXXXXXXXX..
        .....XXXXXXXXXXXXXXX..
        ....XXXXXXXXXXXXXXXX..
        ...XXXXXXXXXXXXXXXXX..
        ..XXXXXXXXXXXXXXXXXX..
        ...XXXXXXXXXXXXXXXXX..
        ....XXXXXXXXXXXXXXXX..
        .....XXXXXXXXXXXXXXX..
        ......XXXXXXXXXXXXXX..
        .......XXXX...........
        ........XXX...........
        .........XX...........
        ..........X...........
        ......................
        ......................
        ......................
    } { . trans  X  black } d { X gray }


    mkicon ::marsgui::icon::forward {
        ......................
        ......................
        ...........X..........
        ...........XX.........
        ...........XXX........
        ...........XXXX.......
        ..XXXXXXXXXXXXXX......
        ..XXXXXXXXXXXXXXX.....
        ..XXXXXXXXXXXXXXXX....
        ..XXXXXXXXXXXXXXXXX...
        ..XXXXXXXXXXXXXXXXXX..
        ..XXXXXXXXXXXXXXXXX...
        ..XXXXXXXXXXXXXXXX....
        ..XXXXXXXXXXXXXXX.....
        ..XXXXXXXXXXXXXX......
        ...........XXXX.......
        ...........XXX........
        ...........XX.........
        ...........X..........
        ......................
        ......................
        ......................
    } { . trans  X  black } d { X gray }

    mkicon ::marsgui::icon::reload {
        .........X......X......
        .........XX......XX....
        .........XXX......XX...
        .......XXXXXX......XX..
        .....XXXXXXXXX......XX.
        ....XXXXXXXXXXX.....XX.
        ..XXXXXXXXXXXX.......XX
        .XXXXXXXXXXXX........XX
        .XXXX....XXX.........XX
        XXXX.....XX...X.....XXX
        XXX......X...XX....XXXX
        XX..........XXX...XXXX.
        XX.........XXXXXXXXXXX.
        XX........XXXXXXXXXXX..
        .XX......XXXXXXXXXXX...
        .XX.......XXXXXXXXX....
        ..XX.......XXXXXX......
        ...XX.......XXX........
        ....XX.......XX........
        ......X.......X........
    } { . trans X black } d { X gray }

    mkicon ::marsgui::icon::folder12 {
        ............
        ......XXXX..
        .....X,,,,X.
        XXXXXXXXXXXX
        X,,,,,,,,,,X
        X,,,,,,,,,,X
        X,,,,,,,,,,X
        X,,,,,,,,,,X
        X,,,,,,,,,,X
        X,,,,,,,,,,X
        X,,,,,,,,,,X
        XXXXXXXXXXXX
    } { . trans X black , "#0AAEBD" }

    mkicon ::marsgui::icon::page12 {
        ....XXXXXXXX
        ...XX,,,,,,X
        ..X,X,,,,,,X
        .X,,X,,,,,,X
        XXXXX,,,,,,X
        X,,,,,,,,,,X
        X,,,,,,,,,,X
        X,,,,,,,,,,X
        X,,,,,,,,,,X
        X,,,,,,,,,,X
        X,,,,,,,,,,X
        XXXXXXXXXXXX
    } { . trans X black , white }

    mkicon ::marsgui::icon::help12 {
        ...XXXXXX...
        ..XX....XX..
        ..XX.....XX.
        ........XX..
        .......XX...
        ......XX....
        .....XX.....
        .....XX.....
        ............
        .....XX.....
        ....XXXX....
        .....XX.....
    } { . trans X black , white }

    mkicon ::marsgui::icon::left_ptr {
        X..........
        XX.........
        XXX........
        XXXX.......
        XXXXX......
        XXXXXX.....
        XXXXXXX....
        XXXXXXXX...
        XXXXXXXXX..
        XXXXXXXXXX.
        XXXXXXXXXXX
        XXXXXXX....
        XXX.XXXX...
        XX..XXXX...
        X....XXXX..
        .....XXXX..
        ......XXXX.
        ......XXXX.
    } { . trans  X black } d { X gray }

    mkicon ::marsgui::icon::fleur {
        ..........X..........
        .........XXX.........
        ........XXXXX........
        .......XXXXXXX.......
        ......XXXXXXXXX......
        ..........X..........
        ....X.....X.....X....
        ...XX.....X.....XX...
        ..XXX.....X.....XXX..
        .XXXX.....X.....XXXX.
        XXXXXXXXXXXXXXXXXXXXX
        .XXXX.....X.....XXXX.
        ..XXX.....X.....XXX..
        ...XX.....X.....XX...
        ....X.....X.....X....
        ..........X..........
        ......XXXXXXXXX......
        .......XXXXXXX.......
        ........XXXXX........
        .........XXX.........
        ..........X..........
    } { . trans  X black } d { X gray }

    mkicon ::marsgui::icon::crosshair {
        ........XX........
        ........XX........
        ........XX........
        ........XX........
        ........XX........
        ........XX........
        ..................
        ..................
        XXXXXX..XX..XXXXXX
        XXXXXX..XX..XXXXXX
        ..................
        ..................
        ........XX........
        ........XX........
        ........XX........
        ........XX........
        ........XX........
        ........XX........
    } { . trans  X black } d { X gray }

    mkicon ::marsgui::icon::poly {
        ..XX..........
        ..X.XX........
        ..X...XX......
        ..X.....XX....
        .X........XX..
        .X..........XX
        .X...........X
        .X...........X
        X............X
        X............X
        X............X
        X............X
        .X...........X
        .X...........X
        .X...........X
        .X.........XXX
        ..X.....XXX...
        ..X..XXX......
        ..XXX.........
    } { . trans  X black } d { X gray }

    mkicon ::marsgui::icon::openfile {
        ...................
        ..XXXXXX...........
        ..X,,,,X...........
        .X,,,,,XXXXXXXX....
        .X,,,,,,,,,,,,,X...
        .X,,,,,,,,,,,,,X...
        .X,,,XXXXXXXXXXXXXX
        .X,,,X,,,,,,,,,,,,X
        .X,,X,,,,,,,,,,,,X.
        .X,,X,,,,,,,,,,,,X.
        .X,X,,,,,,,,,,,,X..
        .X,X,,,,,,,,,,,,X..
        .X,X,,,,,,,,,,,,X..
        .XX,,,,,,,,,,,,X...
        .XX,,,,,,,,,,,,X...
        .XX,,,,,,,,,,,,X...
        .X,,,,,,,,,,,,X....
        .X,,,,,,,,,,,,X....
        .XXXXXXXXXXXXXX....
        ...................
    } { 
        . trans 
        X black
        , #FFCC66
    } d { 
        X #999999
        , #CCCCCC
    }

    mkicon ::marsgui::icon::newfile {
        ...................
        .....XXXXXXXXXXX...
        ....X,X,,,,,,,,X...
        ...X,,X,,,,,XX,X...
        ..X,,,X,,,,,XX,X...
        .XXXXXX,,,,,XX,X...
        .X,,,,,,,XXXXXXXXX.
        .X,,,,,,,XXXXXXXXX.
        .X,,,,,,,,,,XX,X...
        .X,,,,,,,,,,XX,X...
        .X,,,,,,,,,,XX,X...
        .X,,,,,,,,,,,,,X...
        .X,,,,,,,,,,,,,X...
        .X,,,,,,,,,,,,,X...
        .X,,,,,,,,,,,,,X...
        .X,,,,,,,,,,,,,X...
        .X,,,,,,,,,,,,,X...
        .X,,,,,,,,,,,,,X...
        .XXXXXXXXXXXXXXX...
        ...................
    } { 
        . trans 
        X black
        , white
    } d { 
        X #999999
        , #CCCCCC
    }

    mkicon ::marsgui::icon::savefile {
        ...................
        .XXXXXXXXXXXXXXX...
        .XX,,,,,,,,,,,XX...
        .XX,,,,,,,,,,,XX...
        .XX,,,,,,,,,,,XX...
        .XX,,,,,,,,,,,XX...
        .XX,,,,,,,,,,,XX...
        .XX,,,,,,,,,,,XX...
        .XX,,,,,,,,,,,XX...
        .XXXXXXXXXXXXXXX...
        .XXXXXXXXXXXXXXX...
        .XXXX//////XXXXX...
        .XXXX/XX///XXXXX...
        .XXXX/XX///XXXXX...
        .XXXX/XX///XXXXX...
        .XXXX/XX///XXXXX...
        .XXXX//////XXXXX...
        .XXXX//////XXXXX...
        .XXXXXXXXXXXXXXX...
        ...................
    } { 
        . trans 
        X black
        , white
        / gray
    } d { 
        X #999999
    }

    mkicon ::marsgui::icon::handle {
        XXXXXXX
        XXXXXXX
        XXXXXXX
        XXXXXXX
        XXXXXXX
        XXXXXXX
        XXXXXXX
    } {
        X #000000
    }

    mkicon ::marsgui::icon::list22 {
        ......................
        ......................
        ......................
        ...XXXXXXXXXXXXXXXX...
        ......................
        ...XXXXXXXXXXXXXXXX...
        ......................
        ...XXXXXXXXXXXXXXXX...
        ......................
        ......................
        ......................
        ...XXXXXXXXXXXXXXXX...
        ......................
        ...XXXXXXXXXXXXXXXX...
        ......................
        ...XXXXXXXXXXXXXXXX...
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
    } {
        .  trans
        X  #000000
    }

    mkicon ::marsgui::icon::mc22 {
        ......................
        ......................
        ......................
        ...XXXX..XXXX..XXXX...
        ......................
        ...XXXX..XXXX..XXXX...
        ......................
        ...XXXX..XXXX..XXXX...
        ......................
        ...XXXX..XXXX..XXXX...
        ......................
        ...XXXX..XXXX..XXXX...
        ......................
        ...XXXX..XXXX..XXXX...
        ......................
        ...XXXX..XXXX..XXXX...
        ......................
        ...XXXX..XXXX..XXXX...
        ......................
        ...XXXX..XXXX..XXXX...
        ......................
        ......................
    } {
        .  trans
        X  #000000
    }

}

